USE trusticle_db;

INSERT INTO fake_keywords (keyword) VALUES
('100% accurate'),
('100% authentic'),
('100% confirmed'),
('100% factual'),
('100% genuine'),
('100% legitimate'),
('100% proven'),
('100% real'),
('100% true'),
('100% verified'),
('5G cancer'),
('5G danger'),
('5G death'),
('5G disease'),
('5G illness'),
('5G mind control'),
('5G monitoring'),
('5G radiation'),
('5G surveillance'),
('5G tracking'),
('AI generated images'),
('AI-generated propaganda'),
('abduction'),
('aborted fetal cells'),
('absolute proof'),
('abused'),
('according to gossip'),
('according to hearsay'),
('according to insiders'),
('according to leaks'),
('according to rumors'),
('according to rumours'),
('according to speculation'),
('according to whistleblowers'),
('activated'),
('adoration'),
('ad hominem'),
('advertorial'),
('agenda 2030'),
('agent'),
('agent provocateur'),
('agitprop'),
('agroterrorist'),
('alarmism'),
('alert'),
('alien'),
('algorithm bias'),
('algorithm censorship'),
('algorithm control'),
('algorithm filtering'),
('algorithm manipulation'),
('algorithm suppression'),
('allegedly'),
('altered'),
('alternate reality'),
('alternative facts'),
('alternative medicine suppressed'),
('alternative news'),
('amazing'),
('ambushed'),
('amplified'),
('anecdotal evidence'),
('ancient astronauts'),
('angle'),
('annihilated'),
('anons'),
('anonymized'),
('anonymous'),
('anonymous sources'),
('anti-intellectualism'),
('anti-science'),
('anti-vax'),
('apocalypse'),
('apocalyptic'),
('apparently'),
('appeal to emotion'),
('armageddon'),
('aristocrats'),
('artificial'),
('artificial crisis'),
('assaulted'),
('asset seizure imminent'),
('astounding'),
('astro turf'),
('astro turfed'),
('astrological prediction'),
('astroturf'),
('astroturf campaign'),
('attacked'),
('authenticated'),
('authorities'),
('avalanched'),
('avoided'),
('awakening'),
('backdoor'),
('backdoored'),
('backfire effect'),
('bait and switch'),
('ballot dumping'),
('ballot harvesting'),
('ballot stuffing'),
('bandwagon effect'),
('bank account confiscation imminent'),
('bank account freeze imminent'),
('bank account seizure imminent'),
('bank collapse imminent'),
('bank failure imminent'),
('bank run imminent'),
('banned'),
('based'),
('bent'),
('betrayal'),
('bewitchment'),
('bias'),
('biased'),
('biblical prophecy'),
('big agra conspiracy'),
('big food conspiracy'),
('big pharma control'),
('big pharma conspiracy'),
('big pharma corruption'),
('big pharma coverup'),
('big pharma deception'),
('big pharma fraud'),
('big pharma greed'),
('big pharma lies'),
('big pharma manipulation'),
('big pharma profits'),
('big tech conspiracy'),
('bio-weapon'),
('biological terrorist'),
('bioterrorist'),
('black budget project'),
('black listed'),
('black ops'),
('black pill'),
('black propaganda'),
('blackout'),
('blacklist'),
('blind side'),
('blind spot'),
('blindsided'),
('blocked'),
('blood libel'),
('blue pill'),
('blurred'),
('bogus'),
('bombshell'),
('boomer'),
('bootleg'),
('bot army'),
('bot farm'),
('bot net'),
('botware'),
('brainwashed'),
('branded'),
('breadcrumbs'),
('breached'),
('breaking'),
('broken'),
('bubble'),
('burner account'),
('burner phone'),
('cabal'),
('called it'),
('camouflaged'),
('cancelled'),
('cancerous'),
('cartel'),
('categorized'),
('catastrophe'),
('caught in the act'),
('caught on audio'),
('caught on camera'),
('caught on film'),
('caught on mic'),
('caught on record'),
('caught on surveillance'),
('caught on tape'),
('caught on video'),
('caught red-handed'),
('censored'),
('censorship'),
('ceremony'),
('changed'),
('channeling'),
('character assassination'),
('chemical terrorist'),
('chemtrail'),
('chemtrail aluminum'),
('chemtrail barium'),
('chemtrail chemical'),
('chemtrail flu'),
('chemtrail metal'),
('chemtrail poison'),
('chemtrail spray'),
('chemtrail strontium'),
('chemtrail toxic'),
('chemtrail weather control'),
('cherry-picked data'),
('cherry-picked science'),
('cherrypicked'),
('cherrypicking'),
('ciphered'),
('circle'),
('circular'),
('citizen journalist'),
('clairvoyant'),
('clandestine'),
('classified'),
('cleaned'),
('cleansed'),
('click farm'),
('click trapped'),
('clickbait'),
('climate alarmism'),
('climate deception'),
('climate fear-mongering'),
('climate fraud'),
('climate hoax'),
('climate hysteria'),
('climate lie'),
('climate manipulation'),
('climate propaganda'),
('climate scam'),
('clique'),
('cloaked'),
('clone'),
('cloned'),
('cloned account'),
('clown world'),
('clouded'),
('coded'),
('codeword'),
('cognitive'),
('cognitive dissonance reduction'),
('cognitive warfare'),
('coincidence theorist'),
('coincidence theory'),
('Common Core conspiracy'),
('compromised'),
('computational propaganda'),
('concealed'),
('concern trolling'),
('conclusive proof'),
('concrete proof'),
('conditioned'),
('confidential'),
('confidential sources'),
('confined'),
('confirmation'),
('confirmation bias'),
('confirmed'),
('conspiracism'),
('conspiracy'),
('conspiracy theory'),
('conspiratorial thinking'),
('constrained'),
('contactee'),
('contagion'),
('contagious'),
('contained'),
('contaminated'),
('contamination'),
('content moderation bias'),
('content moderation censorship'),
('content moderation control'),
('content moderation filtering'),
('content moderation suppression'),
('contextualized'),
('controversial'),
('convinced'),
('converted'),
('coordinated inauthentic behavior'),
('cope'),
('copied'),
('corroborated'),
('corrupt'),
('corrupted'),
('cosmopolitans'),
('coterie'),
('counter-information'),
('counter-narrative'),
('counterfeited'),
('counterintelligence'),
('cover story'),
('cover-up'),
('cover-up operation'),
('covered up'),
('covert'),
('covert operation'),
('cracked'),
('crash test'),
('credible sources'),
('creed'),
('crew'),
('crime think'),
('crisis'),
('crisis actors'),
('crisis exploitation'),
('crisis pregnancy center'),
('crisis propaganda'),
('critical thinking'),
('crooked'),
('crystal healing'),
('cult'),
('cult-like'),
('cultish'),
('culture war'),
('curated'),
('curated narrative'),
('currency reset imminent'),
('curse'),
('cutout'),
('cyber-espionage'),
('cyberterrorist'),
('damage control'),
('danger'),
('dangerous'),
('dark PR'),
('dark patterns'),
('dark web'),
('data dredging'),
('data void'),
('day one hack'),
('de banked'),
('dead drop'),
('dead letter'),
('deadly'),
('deboosted'),
('debunked'),
('debt cancellation imminent'),
('debt elimination imminent'),
('debt forgiveness imminent'),
('debt jubilee imminent'),
('deceived'),
('deception'),
('deceptive'),
('decimated'),
('decontaminated'),
('decontextualized'),
('deep cover'),
('deep dive'),
('deep state'),
('deep web'),
('deepfake'),
('deepfake audio'),
('deepfake celebrity'),
('deepfake video'),
('defamed'),
('definitive proof'),
('defund science'),
('deification'),
('deified'),
('deindividuation'),
('delegitimized'),
('deleted'),
('delusion'),
('demonetized'),
('demonized'),
('demolished'),
('denialism'),
('denialist tactics'),
('deplatformed'),
('depopulation'),
('depopulation agenda'),
('deranked'),
('destined'),
('destroyed'),
('detained'),
('detox'),
('detoxified'),
('devotion'),
('digital gaslighting'),
('digital wildfire'),
('directed energy weapon'),
('dis connected'),
('disappeared'),
('disaster'),
('disclosure'),
('discredited'),
('discredited scientist'),
('diseased'),
('disinfected'),
('disinformation'),
('disinformation agent'),
('disinformation campaign'),
('dismissed'),
('dissonance'),
('distorted'),
('distributed'),
('distrust of experts'),
('divided'),
('do your own research'),
('doctored'),
('doctrine'),
('dodgy'),
('dogma'),
('dollar collapse imminent'),
('dominated'),
('doomer'),
('doomsday'),
('doppel account'),
('doppelganger'),
('dormant'),
('double speak'),
('downplayed'),
('dreaded'),
('dreamed'),
('dubious'),
('Dunning-Kruger effect'),
('duplicated'),
('echo chamber'),
('echo chamber reinforcement'),
('echoed'),
('economic collapse imminent'),
('economic reset imminent'),
('ecoterrorist'),
('edited'),
('education brainwashing'),
('education Common Core conspiracy'),
('education conditioning'),
('education dumbing down'),
('education indoctrination'),
('education manipulation'),
('education mind control'),
('education programming'),
('education social engineering'),
('education propaganda'),
('election fraud'),
('election interference'),
('election manipulation'),
('election theft'),
('elite'),
('elite agenda'),
('elitists'),
('eliminated'),
('EMF weapon'),
('emergency'),
('emotional contagion'),
('emotional reasoning'),
('enabler'),
('enchantment'),
('encrypted'),
('end of the world'),
('end times'),
('engineered'),
('engineered crisis'),
('engineered dissent'),
('engineered opposition'),
('engineered virality'),
('engineered virus'),
('engagement bait'),
('enslaved'),
('entertainer'),
('energy healing'),
('epidemic'),
('eradicated'),
('erased'),
('escaped'),
('espionage'),
('establishment'),
('evaded'),
('evidence'),
('everything you know is a lie'),
('exaggerated'),
('excluded'),
('exclusive'),
('exclusive sources'),
('exorcism'),
('experiencer'),
('expert'),
('exploited'),
('explosive'),
('explosive terrorist'),
('exposed'),
('exposed anonymous'),
('exposed audio'),
('exposed classified'),
('exposed confidential'),
('exposed data'),
('exposed document'),
('exposed email'),
('exposed file'),
('exposed image'),
('exposed information'),
('exposed insider'),
('exposed intelligence'),
('exposed internal'),
('exposed letter'),
('exposed memo'),
('exposed photo'),
('exposed picture'),
('exposed private'),
('exposed recording'),
('exposed report'),
('exposed screenshot'),
('exposed secret'),
('exposed source'),
('exposed undisclosed'),
('exposed video'),
('expunged'),
('exterminated'),
('extinguished'),
('extraterrestrial'),
('extremist'),
('eyesopen'),
('fabricated'),
('fabrication'),
('facilitator'),
('facsimile'),
('fact-check'),
('fact-check bias'),
('fact-check censorship'),
('fact-check control'),
('fact-check filtering'),
('fact-check suppression'),
('fact-checkers agenda'),
('fact-checkers bias'),
('fact-checkers censorship'),
('fact-checkers conspiracy'),
('fact-checkers control'),
('fact-checkers coverup'),
('fact-checkers deception'),
('fact-checkers lies'),
('fact-checkers manipulation'),
('fact-checkers propaganda'),
('faction'),
('fake'),
('fake account'),
('fake crisis'),
('fake expert'),
('fake news'),
('fake opposition'),
('fake pandemic'),
('fakery'),
('fall guy'),
('fall person'),
('false'),
('false attribution'),
('false consensus'),
('false crisis'),
('false equivalence'),
('false flag'),
('false flag operation'),
('false front'),
('false grassroots'),
('false grassroots movement'),
('false memory'),
('false messiahs'),
('false opposition'),
('false prophet'),
('false scarcity'),
('false utopia'),
('fanatic'),
('fantasized'),
('fatal'),
('fear'),
('fear factor'),
('fear porn'),
('fear-mongering'),
('feared'),
('fed'),
('fedposting'),
('fifth column'),
('filtered'),
('filter bubble'),
('final days'),
('financial crash imminent'),
('financial reset imminent'),
('financial system scam'),
('fishbowl'),
('fishy'),
('fixed'),
('flat earth'),
('flooded'),
('flying saucer'),
('fogged'),
('followthemoney'),
('following'),
('food crisis planned'),
('food insecurity planned'),
('food scarcity planned'),
('food shortage planned'),
('food supply contamination planned'),
('food supply control planned'),
('food supply destruction planned'),
('food supply disruption planned'),
('food supply manipulation planned'),
('food supply poisoning planned'),
('forbidden'),
('forbidden archaeology'),
('forbidden history'),
('forecast'),
('forecast accurate'),
('forecasted'),
('foreseen'),
('foretold'),
('forgery'),
('formaldehyde'),
('fortune telling'),
('found anonymous'),
('found audio'),
('found classified'),
('found confidential'),
('found data'),
('found document'),
('found email'),
('found file'),
('found image'),
('found information'),
('found insider'),
('found intelligence'),
('found internal'),
('found letter'),
('found memo'),
('found photo'),
('found picture'),
('found private'),
('found recording'),
('found report'),
('found screenshot'),
('found secret'),
('found source'),
('found undisclosed'),
('found video'),
('fractured'),
('fragmented'),
('framed'),
('framing'),
('fraudulent'),
('free energy device'),
('freeman on the land'),
('frenzy'),
('front organization'),
('frontdoor'),
('FUD'),
('fundamentalist'),
('furtive'),
('gag order'),
('gagged'),
('gain of function'),
('gamed'),
('gang'),
('gang stalking'),
('garbage'),
('gas lighting'),
('gaslighting tactics'),
('gatekeepers'),
('genocidal'),
('geoengineering'),
('ghost ban'),
('ghostwriting'),
('gibberish'),
('Gish gallop'),
('global anarchism'),
('global anarchism advocates'),
('global aristocrats'),
('global aristocrats advocates'),
('global authorities'),
('global authorities advocates'),
('global authoritarianism'),
('global authoritarianism advocates'),
('global betrayal'),
('global betrayal advocates'),
('global bureaucrats'),
('global bureaucrats advocates'),
('global cabal'),
('global cabal advocates'),
('global cartel'),
('global cartel advocates'),
('global circle'),
('global circle advocates'),
('global clique'),
('global clique advocates'),
('global communism'),
('global communism advocates'),
('global con'),
('global con advocates'),
('global conquest'),
('global conquest advocates'),
('global conspiracy'),
('global conspiracy advocates'),
('global control'),
('global control advocates'),
('global cosmopolitans'),
('global cosmopolitans advocates'),
('global coterie'),
('global coterie advocates'),
('global crew'),
('global crew advocates'),
('global deception'),
('global deception advocates'),
('global dictatorship'),
('global dictatorship advocates'),
('global domination'),
('global domination advocates'),
('global elite'),
('global elite advocates'),
('global elitists'),
('global elitists advocates'),
('global enslavement'),
('global enslavement advocates'),
('global establishment'),
('global establishment advocates'),
('global extremism'),
('global extremism advocates'),
('global fanaticism'),
('global fanaticism advocates'),
('global fascism'),
('global fascism advocates'),
('global fraud'),
('global fraud advocates'),
('global fundamentalism'),
('global fundamentalism advocates'),
('global gang'),
('global gang advocates'),
('global globalists'),
('global globalists advocates'),
('global government'),
('global government advocates'),
('global hoax'),
('global hoax advocates'),
('global insurgency'),
('global insurgency advocates'),
('global insurrection'),
('global insurrection advocates'),
('global internationalists'),
('global internationalists advocates'),
('global leninism'),
('global leninism advocates'),
('global mafia'),
('global mafia advocates'),
('global maoism'),
('global maoism advocates'),
('global marxism'),
('global marxism advocates'),
('global militancy'),
('global militancy advocates'),
('global mob'),
('global mob advocates'),
('global mutiny'),
('global mutiny advocates'),
('global nazism'),
('global nazism advocates'),
('global nihilism'),
('global nihilism advocates'),
('global officials'),
('global officials advocates'),
('global oligarchs'),
('global oligarchs advocates'),
('global order'),
('global order advocates'),
('global plot'),
('global plot advocates'),
('global plutocrats'),
('global plutocrats advocates'),
('global posse'),
('global posse advocates'),
('global power'),
('global power advocates'),
('global powers'),
('global powers advocates'),
('global radicalism'),
('global radicalism advocates'),
('global rebellion'),
('global rebellion advocates'),
('global regime'),
('global regime advocates'),
('global revolt'),
('global revolt advocates'),
('global revolution'),
('global revolution advocates'),
('global scam'),
('global scam advocates'),
('global scheme'),
('global scheme advocates'),
('global sedition'),
('global sedition advocates'),
('global socialism'),
('global socialism advocates'),
('global stalinism'),
('global stalinism advocates'),
('global subjugation'),
('global subjugation advocates'),
('global swindle'),
('global swindle advocates'),
('global syndicate'),
('global syndicate advocates'),
('global system'),
('global system advocates'),
('global takeover'),
('global takeover advocates'),
('global technocrats'),
('global technocrats advocates'),
('global terrorism'),
('global terrorism advocates'),
('global totalitarianism'),
('global totalitarianism advocates'),
('global treason'),
('global treason advocates'),
('global trotskyism'),
('global trotskyism advocates'),
('global tyranny'),
('global tyranny advocates'),
('global uprising'),
('global uprising advocates'),
('global warming alarmism'),
('global warming deception'),
('global warming fear-mongering'),
('global warming fraud'),
('global warming hoax'),
('global warming hysteria'),
('global warming lie'),
('global warming manipulation'),
('global warming propaganda'),
('global warming scam'),
('global zealotry'),
('global zealotry advocates'),
('globalist agenda'),
('globalists'),
('glowie'),
('GMO cancer'),
('GMO danger'),
('GMO death'),
('GMO disease'),
('GMO illness'),
('GMO infertility'),
('GMO poison'),
('GMO population control'),
('GMO sterility'),
('GMO toxic'),
('government conspiracy'),
('government coverup'),
('government deception'),
('government lies'),
('government mind control'),
('government plot'),
('government propaganda'),
('grapevine'),
('great reset'),
('greed'),
('grey propaganda'),
('grey state'),
('griefploitation'),
('group polarization'),
('group think'),
('HAARP'),
('hacked'),
('hacked anonymous'),
('hacked audio'),
('hacked classified'),
('hacked confidential'),
('hacked data'),
('hacked document'),
('hacked email'),
('hacked file'),
('hacked image'),
('hacked information'),
('hacked insider'),
('hacked intelligence'),
('hacked internal'),
('hacked letter'),
('hacked memo'),
('hacked photo'),
('hacked picture'),
('hacked private'),
('hacked recording'),
('hacked report'),
('hacked screenshot'),
('hacked secret'),
('hacked source'),
('hacked undisclosed'),
('hacked video'),
('hallucination'),
('hand waved'),
('handler'),
('hard proof'),
('hardened'),
('harmful'),
('hashed'),
('health freedom'),
('hearsay evidence'),
('held captive'),
('herd immunity'),
('herd mentality'),
('hex'),
('hidden'),
('hidden agenda'),
('hidden history'),
('hidden knowledge'),
('hidden motive'),
('hidden truth'),
('high-pressure sales tactics'),
('hired actors'),
('historical denial'),
('historical event coverup'),
('historical event deception'),
('historical event fake'),
('historical event fabricated'),
('historical event falsified'),
('historical event hoax'),
('historical event lie'),
('historical event manipulated'),
('historical event propaganda'),
('historical event staged'),
('history coverup'),
('history deception'),
('history distorted'),
('history fabricated'),
('history falsified'),
('history lie'),
('history manipulated'),
('history propaganda'),
('history revised'),
('history rewritten'),
('hive mind'),
('hoax'),
('hoax crisis'),
('holistic medicine suppressed'),
('hollow earth'),
('homeopathy suppressed'),
('honeypot'),
('honeypot scheme'),
('honeytrap'),
('horror'),
('hunting'),
('hype'),
('hyper-partisan'),
('hyper-skepticism'),
('hyperinflation imminent'),
('hypnosis'),
('hypnotized'),
('hypocrisy'),
('hypocritical'),
('hypothetical'),
('hysteria'),
('identity politics'),
('idolization'),
('idolatry'),
('ignored'),
('illuminati'),
('illusion'),
('illusory truth effect'),
('imagined'),
('imitation'),
('imminent'),
('impersonation account'),
('impersonator'),
('important'),
('impostor'),
('imprisoned'),
('in-group favoritism'),
('inactive'),
('incarcerated'),
('incredible'),
('independent media'),
('indoctrinated'),
('inevitable'),
('inescapable'),
('infected'),
('infectious'),
('infestation'),
('infiltration'),
('infodemic'),
('influence peddling'),
('influence operation'),
('influenced'),
('infoop'),
('infomercial'),
('information blackout'),
('information cascade'),
('information hygiene'),
('information laundering'),
('information overload'),
('information pollution'),
('information silo'),
('information warfare'),
('infovirus'),
('infowar'),
('inner circle'),
('insanity'),
('inside job'),
('insider'),
('inside sources'),
('intelligence'),
('intermediary'),
('international anarchism'),
('international anarchism advocates'),
('international aristocrats'),
('international aristocrats advocates'),
('international authorities'),
('international authorities advocates'),
('international authoritarianism'),
('international authoritarianism advocates'),
('international betrayal'),
('international betrayal advocates'),
('international bureaucrats'),
('international bureaucrats advocates'),
('international cabal'),
('international cabal advocates'),
('international cartel'),
('international cartel advocates'),
('international circle'),
('international circle advocates'),
('international clique'),
('international clique advocates'),
('international communism'),
('international communism advocates'),
('international con'),
('international con advocates'),
('international conquest'),
('international conquest advocates'),
('international conspiracy'),
('international conspiracy advocates'),
('international control'),
('international control advocates'),
('international cosmopolitans'),
('international cosmopolitans advocates'),
('international coterie'),
('international coterie advocates'),
('international crew'),
('international crew advocates'),
('international deception'),
('international deception advocates'),
('international dictatorship'),
('international dictatorship advocates'),
('international domination'),
('international domination advocates'),
('international elite'),
('international elite advocates'),
('international elitists'),
('international elitists advocates'),
('international enslavement'),
('international enslavement advocates'),
('international establishment'),
('international establishment advocates'),
('international extremism'),
('international extremism advocates'),
('international fanaticism'),
('international fanaticism advocates'),
('international fascism'),
('international fascism advocates'),
('international fraud'),
('international fraud advocates'),
('international fundamentalism'),
('international fundamentalism advocates'),
('international gang'),
('international gang advocates'),
('international globalists'),
('international globalists advocates'),
('international government'),
('international government advocates'),
('international hoax'),
('international hoax advocates'),
('international insurgency'),
('international insurgency advocates'),
('international insurrection'),
('international insurrection advocates'),
('international internationalists'),
('international internationalists advocates'),
('international leninism'),
('international leninism advocates'),
('international mafia'),
('international mafia advocates'),
('international maoism'),
('international maoism advocates'),
('international marxism'),
('international marxism advocates'),
('international militancy'),
('international militancy advocates'),
('international mob'),
('international mob advocates'),
('international mutiny'),
('international mutiny advocates'),
('international nazism'),
('international nazism advocates'),
('international nihilism'),
('international nihilism advocates'),
('international officials'),
('international officials advocates'),
('international oligarchs'),
('international oligarchs advocates'),
('international order'),
('international order advocates'),
('international plot'),
('international plot advocates'),
('international plutocrats'),
('international plutocrats advocates'),
('international posse'),
('international posse advocates'),
('international power'),
('international power advocates'),
('international powers'),
('international powers advocates'),
('international radicalism'),
('international radicalism advocates'),
('international rebellion'),
('international rebellion advocates'),
('international regime'),
('international regime advocates'),
('international revolt'),
('international revolt advocates'),
('international revolution'),
('international revolution advocates'),
('international scam'),
('international scam advocates'),
('international scheme'),
('international scheme advocates'),
('international sedition'),
('international sedition advocates'),
('international socialism'),
('international socialism advocates'),
('international stalinism'),
('international stalinism advocates'),
('international subjugation'),
('international subjugation advocates'),
('international swindle'),
('international swindle advocates'),
('international syndicate'),
('international syndicate advocates'),
('international system'),
('international system advocates'),
('international takeover'),
('international takeover advocates'),
('international technocrats'),
('international technocrats advocates'),
('international terrorism'),
('international terrorism advocates'),
('international totalitarianism'),
('international totalitarianism advocates'),
('international treason'),
('international treason advocates'),
('international trotskyism'),
('international trotskyism advocates'),
('international tyranny'),
('international tyranny advocates'),
('international uprising'),
('international uprising advocates'),
('international zealotry'),
('international zealotry advocates'),
('internationalists'),
('invalidated'),
('inverse reality'),
('invisible'),
('irrefutable proof'),
('isolated'),
('jail breaked'),
('jailbroken'),
('jaw-dropping'),
('judgment day'),
('junk'),
('junk science'),
('key logger'),
('killer'),
('kompromat'),
('lab leak theory'),
('labeled'),
('LARPing'),
('last days'),
('laundered'),
('leaked'),
('leaked anonymous'),
('leaked audio'),
('leaked classified'),
('leaked confidential'),
('leaked data'),
('leaked document'),
('leaked email'),
('leaked file'),
('leaked image'),
('leaked information'),
('leaked insider'),
('leaked intelligence'),
('leaked internal'),
('leaked letter'),
('leaked memo'),
('leaked photo'),
('leaked picture'),
('leaked private'),
('leaked recording'),
('leaked report'),
('leaked screenshot'),
('leaked secret'),
('leaked source'),
('leaked undisclosed'),
('leaked video'),
('lethal'),
('libeled'),
('limited'),
('limited hangout'),
('lizard people'),
('logical fallacy'),
('lone wolf'),
('look alike'),
('lost'),
('lunacy'),
('madness'),
('mafia'),
('mainstream media lies'),
('malignant'),
('malinformation'),
('malware'),
('Mandela effect'),
('mania'),
('manipulated'),
('manufactured'),
('manufactured consent'),
('manufactured crisis'),
('manufactured doubt'),
('manufactured opposition'),
('marginalized'),
('marked'),
('market crash imminent'),
('masked'),
('mass formation psychosis'),
('mastermind'),
('maximized'),
('media bias'),
('media blackout'),
('media brainwashing'),
('media censorship'),
('media conditioning'),
('media conspiracy'),
('media control'),
('media coverup'),
('media deception'),
('media literacy'),
('media manipulation'),
('media programming'),
('media propaganda'),
('media silence'),
('media suppression'),
('medical freedom'),
('medium'),
('memed'),
('meme warfare'),
('memetic'),
('memory hole'),
('memory holed'),
('memory holing'),
('mercenary'),
('messiah complex'),
('microchip implant danger'),
('microchip implant monitoring'),
('microchip implant surveillance'),
('microchip implant tracking'),
('middle man'),
('militant'),
('mimetic'),
('mind control'),
('mind-blowing'),
('mind-controlled'),
('minimized'),
('miracle'),
('miracle cure'),
('miracle diet'),
('miracle food'),
('miracle healing'),
('miracle herb'),
('miracle plant'),
('miracle recovery'),
('miracle remedy'),
('miracle supplement'),
('miracle treatment'),
('mirror account'),
('mirror world'),
('mirrored'),
('misinformation'),
('misinterpreted study'),
('misleading'),
('misleading statistics'),
('missing'),
('MKUltra'),
('mob'),
('mockingbird'),
('modeled'),
('modern myth'),
('modified'),
('monitoring'),
('moon landing hoax'),
('moral outrage'),
('moral panic'),
('morgellons disease'),
('motivated reasoning'),
('msmlies'),
('muckraking'),
('muddied'),
('multiplied'),
('murderous'),
('must know'),
('must read'),
('must see'),
('must share'),
('must watch'),
('muzzled'),
('nanobots'),
('narcoterrorist'),
('narrative'),
('narrative warfare'),
('native advertising'),
('natural cure suppressed'),
('natural healing suppressed'),
('natural immunity'),
('natural remedy suppressed'),
('natural treatment suppressed'),
('naturopathy suppressed'),
('neuro-linguistic programming'),
('new speak'),
('new world order'),
('new world order advocates'),
('news blackout'),
('news brainwashing'),
('news censorship'),
('news conditioning'),
('news control'),
('news desert'),
('news manipulation'),
('news propaganda'),
('news silence'),
('news suppression'),
('nightmare'),
('nightmared'),
('nonsense'),
('normie'),
('nothingburger'),
('NPC'),
('nuclear terrorist'),
('nullified'),
('numerology'),
('obfuscated'),
('obliterated'),
('obscured'),
('occult ritual'),
('off grid'),
('off system'),
('offering'),
('official narrative debunked'),
('official story'),
('officials'),
('oligarchs'),
('omnipresent'),
('one world government'),
('one world government advocates'),
('one world religion'),
('Operation Paperclip'),
('operation'),
('operative'),
('oppressed'),
('orchestrated'),
('orchestrated crisis'),
('orchestrated opposition'),
('ostensibly'),
('ostracized'),
('out of system'),
('out-group derogation'),
('out-of-context quotes'),
('outbreak'),
('outlier data'),
('outrage bait'),
('outrageous'),
('overlooked'),
('overwhelmed'),
('pacification'),
('paid actors'),
('pandemic'),
('panic'),
('paranormal'),
('parroted'),
('party line'),
('patriot fight'),
('patriot truth'),
('patriots awake'),
('patsy'),
('pay-to-play science'),
('penetrated'),
('penetration'),
('perception management'),
('permeated'),
('perpetrated'),
('perpetual motion machine'),
('persecuted'),
('persecution complex'),
('persuaded'),
('pervasive'),
('perverted'),
('pestilence'),
('phony'),
('photoshopped'),
('pink slime journalism'),
('pirated'),
('plagiarized content'),
('plague'),
('Planet X / Nibiru'),
('plandemic'),
('planted'),
('plausible deniability'),
('poisoned'),
('polarized'),
('political assassination'),
('political cancellation'),
('political censorship'),
('political cleansing'),
('political elimination'),
('political hit job'),
('political persecution'),
('political purge'),
('political silencing'),
('political targeting'),
('political witch hunt'),
('posse'),
('possession'),
('post-fact world'),
('post-reality'),
('post-truth'),
('powers that be'),
('predatory journal'),
('predestined'),
('predictive programming'),
('prediction'),
('prediction coming true'),
('prejudice'),
('prepaid'),
('preprogrammed'),
('pro-plague'),
('Project Mockingbird'),
('projected'),
('proliferated'),
('propaganda'),
('propaganda piece'),
('propagated'),
('prophecy fulfilled'),
('prophecy unfolding'),
('prophesied'),
('prophetic'),
('proven right'),
('pseudo-event'),
('pseudo-skepticism'),
('psychic'),
('psychological operation'),
('psychoterrorist'),
('psychotronic weapons'),
('puppet academic'),
('puppet actor'),
('puppet actress'),
('puppet agency'),
('puppet authority'),
('puppet babble'),
('puppet celebrity'),
('puppet company'),
('puppet conspiracy'),
('puppet contamination'),
('puppet controller'),
('puppet corporation'),
('puppet delusion'),
('puppet disease'),
('puppet doctor'),
('puppet dream'),
('puppet drivel'),
('puppet educator'),
('puppet entertainer'),
('puppet epidemic'),
('puppet expert'),
('puppet fantasy'),
('puppet fear'),
('puppet fiction'),
('puppet figure'),
('puppet frenzy'),
('puppet garbage'),
('puppet gibberish'),
('puppet government'),
('puppet guru'),
('puppet hallucination'),
('puppet handler'),
('puppet hero'),
('puppet horror'),
('puppet hysteria'),
('puppet hypothesis'),
('puppet icon'),
('puppet idol'),
('puppet illusion'),
('puppet infection'),
('puppet influencer'),
('puppet insanity'),
('puppet institution'),
('puppet journalist'),
('puppet junk'),
('puppet leader'),
('puppet lunacy'),
('puppet madness'),
('puppet manipulator'),
('puppet mania'),
('puppet master'),
('puppet media'),
('puppet messiah'),
('puppet narrative'),
('puppet news'),
('puppet nightmare'),
('puppet nonsense'),
('puppet official'),
('puppet operator'),
('puppet opposition'),
('puppet organization'),
('puppet panic'),
('puppet pandemic'),
('puppet personality'),
('puppet plague'),
('puppet plan'),
('puppet player'),
('puppet plot'),
('puppet politician'),
('puppet pollution'),
('puppet president'),
('puppet professor'),
('puppet prophet'),
('puppet regime'),
('puppet reporter'),
('puppet researcher'),
('puppet ridiculousness'),
('puppet rubbish'),
('puppet savior'),
('puppet scientist'),
('puppet scheme'),
('puppet spokesperson'),
('puppet state'),
('puppet story'),
('puppet strings'),
('puppet tale'),
('puppet teacher'),
('puppet terror'),
('puppet theory'),
('puppet trash'),
('puppet waste'),
('purged'),
('purified'),
('puritanical'),
('purity spiral'),
('purportedly'),
('quackery'),
('quantum healing'),
('quarantined'),
('question everything'),
('questionable'),
('rabbit hole'),
('radicalized'),
('radiological terrorist'),
('radioterrorist'),
('rage bait'),
('rapture'),
('real facts'),
('reality apathy'),
('reality distortion field'),
('realstory'),
('recycled news'),
('red pilled'),
('red pill'),
('redacted'),
('redpill'),
('reframing'),
('regime'),
('reliable sources'),
('religious bias'),
('religious censorship'),
('religious discrimination'),
('religious hatred'),
('religious intolerance'),
('religious persecution'),
('religious prejudice'),
('religious silencing'),
('religious suppression'),
('religious targeting'),
('remote neural monitoring'),
('removed'),
('repeated'),
('replica'),
('replicated'),
('reportedly'),
('reptilian elite'),
('reputation attack'),
('reputedly'),
('rescinded'),
('research agenda'),
('research bias'),
('research corruption'),
('research deception'),
('research fraud'),
('research hoax'),
('research lie'),
('research manipulation'),
('research propaganda'),
('research scam'),
('restricted'),
('retracted'),
('revealed'),
('revealed anonymous'),
('revealed audio'),
('revealed classified'),
('revealed confidential'),
('revealed data'),
('revealed document'),
('revealed email'),
('revealed file'),
('revealed image'),
('revealed information'),
('revealed insider'),
('revealed intelligence'),
('revealed internal'),
('revealed letter'),
('revealed memo'),
('revealed photo'),
('revealed picture'),
('revealed private'),
('revealed recording'),
('revealed report'),
('revealed screenshot'),
('revealed secret'),
('revealed source'),
('revealed undisclosed'),
('revealed video'),
('reverence'),
('revisionism'),
('revoked'),
('RFID chip control'),
('RFID chip danger'),
('RFID chip mark of the beast'),
('RFID chip monitoring'),
('RFID chip surveillance'),
('RFID chip tracking'),
('rigged'),
('rigged election'),
('ritual'),
('rogue doctor'),
('rooted'),
('rootkit'),
('rubbish'),
('rumint'),
('rumor'),
('rumor mill'),
('rumored'),
('rumoured'),
('sabotaged'),
('sacrifice'),
('safe house'),
('salted'),
('sanitized'),
('satanic panic'),
('saturated'),
('scam'),
('scamdemic'),
('scandal'),
('scenario planned'),
('sceptic'),
('scheme'),
('science agenda'),
('science bias'),
('science corruption'),
('science deception'),
('science fraud'),
('science hoax'),
('science lie'),
('science manipulation'),
('science propaganda'),
('science scam'),
('scientific consensus agenda'),
('scientific consensus bias'),
('scientific consensus corruption'),
('scientific consensus deception'),
('scientific consensus fraud'),
('scientific consensus hoax'),
('scientific consensus lie'),
('scientific consensus manipulation'),
('scientific consensus propaganda'),
('scientific consensus scam'),
('scientist agenda'),
('scientist bias'),
('scientist corruption'),
('scientist deception'),
('scientist fraud'),
('scientist hoax'),
('scientist lie'),
('scientist manipulation'),
('scientist propaganda'),
('scientist scam'),
('scourge'),
('scrambled'),
('scrubbed'),
('seal-lioning'),
('search blacklist'),
('search bias'),
('search censorship'),
('search manipulation'),
('search whitelist'),
('secret'),
('secret agent'),
('secret agenda'),
('secret cure'),
('secret knowledge'),
('secret motive'),
('secret societies'),
('secret sources'),
('secret space program'),
('secretive'),
('sect'),
('security hole'),
('sedition'),
('seethe'),
('segregated'),
('selective editing'),
('self-published "expert"'),
('selfreferential'),
('selffulfilling'),
('sensationalist'),
('sensationalized'),
('sentiment manipulation'),
('separated'),
('setup'),
('shady'),
('shadow banned'),
('shadow blocking'),
('shadow censorship'),
('shadow control'),
('shadow filtering'),
('shadow government'),
('shadow suppression'),
('sham'),
('shape-shifters'),
('shattered'),
('sheeple'),
('shell corporation'),
('shill'),
('shill bidding'),
('shocking'),
('shocking truth'),
('shrouded'),
('shut down'),
('shut out'),
('shut up'),
('side channel'),
('siege mentality'),
('silence'),
('silenced'),
('silenced expert'),
('silent ban'),
('silent sound spread spectrum'),
('simulacrum'),
('simulated'),
('simulated crisis'),
('single source claim'),
('slandered'),
('slant'),
('slanted'),
('sleeper'),
('sleeper agent'),
('sleeper cell'),
('sleepwalking'),
('slippery slope'),
('smart meter cancer'),
('smart meter danger'),
('smart meter death'),
('smart meter disease'),
('smart meter illness'),
('smart meter monitoring'),
('smart meter radiation'),
('smart meter spying'),
('smart meter surveillance'),
('smart meter tracking'),
('smeared'),
('smoking gun'),
('snake oil'),
('snowballed'),
('social media censorship'),
('social media control'),
('social media filtering'),
('social media manipulation'),
('social media suppression'),
('sock puppet'),
('sockpuppetry'),
('sockpuppet army'),
('softened'),
('solid proof'),
('sources say'),
('sovereign citizen'),
('specialop'),
('spell'),
('spin'),
('spin doctor'),
('spiritual'),
('spoofed account'),
('sponsored content'),
('spread'),
('spy'),
('spyware'),
('staged'),
('staged accident'),
('staged attitude'),
('staged bombing'),
('staged catastrophe'),
('staged circumstance'),
('staged condition'),
('staged conviction'),
('staged creed'),
('staged cult'),
('staged danger'),
('staged disaster'),
('staged doctrine'),
('staged dogma'),
('staged emergency'),
('staged faith'),
('staged hazard'),
('staged ideology'),
('staged jeopardy'),
('staged opinion'),
('staged opposition'),
('staged peril'),
('staged perspective'),
('staged philosophy'),
('staged position'),
('staged posture'),
('staged predicament'),
('staged religion'),
('staged risk'),
('staged shooting'),
('staged situation'),
('staged stance'),
('staged state'),
('staged status'),
('staged threat'),
('staged tragedy'),
('staged viewpoint'),
('stagemanaged'),
('stalking'),
('state-backed hacking'),
('state-sponsored media'),
('stealth'),
('stealth marketing'),
('sterilized'),
('stigmatized'),
('stolen election'),
('storm is coming'),
('strawman'),
('strawman argument'),
('stress test'),
('study agenda'),
('study bias'),
('study corruption'),
('study deception'),
('study fraud'),
('study hoax'),
('study lie'),
('study manipulation'),
('study propaganda'),
('study scam'),
('subjugated'),
('subliminal messaging'),
('substantiated'),
('subterfuge'),
('subversion'),
('subverted'),
('suicide terrorist'),
('supernatural'),
('suppressed'),
('suppressed cure'),
('suppressed technology'),
('suppression'),
('supranational government'),
('surveillance'),
('suspicious'),
('swayed'),
('swindle'),
('syndicate'),
('synthetic'),
('synthetic conflict'),
('synthetic crisis'),
('synthetic media'),
('synthetic outrage'),
('synthetic voice'),
('tagged'),
('tainted'),
('targeted'),
('targeted individual'),
('targeting'),
('tarnished'),
('tarot reading'),
('teacher'),
('technocrats'),
('terrorist'),
('textbook agenda'),
('textbook bias'),
('textbook brainwashing'),
('textbook conditioning'),
('textbook indoctrination'),
('textbook manipulation'),
('textbook mind control'),
('textbook programming'),
('textbook propaganda'),
('textbook social engineering'),
('the chosen one'),
('the great awakening'),
('the great deception'),
('the matrix'),
('the real story'),
('the storm'),
('theoretical'),
('they don''t want you to know this'),
('thought control'),
('thought crime'),
('thought experiment'),
('thought police'),
('thought terminating cliche'),
('thought-stopping'),
('threat'),
('tilt'),
('told you so'),
('top secret'),
('toxic'),
('tracking'),
('tracing'),
('transhumanism'),
('transnational government'),
('trash'),
('trauma'),
('trauma farming'),
('treason'),
('trending'),
('trending censorship'),
('trending control'),
('trending filtering'),
('trending manipulation'),
('trending suppression'),
('tribute'),
('triggerword'),
('trivialized'),
('trojan'),
('trojanized'),
('troll army'),
('troll brigade'),
('troll farm'),
('troll patrol'),
('truman show'),
('trust the plan'),
('trusted sources'),
('truth bomb'),
('truth community'),
('truth decay'),
('truth is out there'),
('truth movement'),
('truth pill'),
('truth revealed'),
('truth seeker'),
('truth teller'),
('truth warrior'),
('truther'),
('tsunamied'),
('twisted'),
('ubiquitous'),
('ufo'),
('ulterior motive'),
('un personed'),
('un plugged'),
('un reported'),
('unauthorized'),
('unavoidable'),
('un banked'),
('unbelievable'),
('uncheckable'),
('unchecked'),
('unconfirmed'),
('uncorroborated'),
('uncovered anonymous'),
('uncovered audio'),
('uncovered classified'),
('uncovered confidential'),
('uncovered data'),
('uncovered document'),
('uncovered email'),
('uncovered file'),
('uncovered image'),
('uncovered information'),
('uncovered insider'),
('uncovered intelligence'),
('uncovered internal'),
('uncovered letter'),
('uncovered memo'),
('uncovered photo'),
('uncovered picture'),
('uncovered private'),
('uncovered recording'),
('uncovered report'),
('uncovered screenshot'),
('uncovered secret'),
('uncovered source'),
('uncovered undisclosed'),
('uncovered video'),
('under reported'),
('undercover'),
('undermined'),
('undeniable proof'),
('undisclosed'),
('undisclosed paid promotion'),
('undisclosed sponsorship'),
('unfalsifiable'),
('unleashed'),
('unlicensed'),
('unnamed'),
('unnamed sources'),
('unpersoning'),
('unprovable'),
('unreliable'),
('unsourced'),
('unsubstantiated'),
('untraceable'),
('unverified'),
('unverified source'),
('urgent'),
('urban legend'),
('us vs them mentality'),
('used'),
('useful idiot'),
('vaccine aborted fetal cells'),
('vaccine aluminum'),
('vaccine autism'),
('vaccine control'),
('vaccine damage'),
('vaccine death'),
('vaccine depopulation'),
('vaccine eugenics'),
('vaccine formaldehyde'),
('vaccine genocide'),
('vaccine injury'),
('vaccine mercury'),
('vaccine microchip'),
('vaccine poison'),
('vaccine population control'),
('vaccine shedding'),
('vaccine sterilization'),
('vaccine surveillance'),
('vaccine toxin'),
('vaccine tracking'),
('validated'),
('vanished'),
('vanity press'),
('veiled'),
('venerated'),
('veneration'),
('venomous'),
('verified'),
('victim blaming'),
('victimized'),
('vilified'),
('vindicated'),
('violated'),
('viral'),
('viral deception'),
('virulent'),
('virtual'),
('virtual crisis'),
('virtue signaling'),
('virus'),
('virus laden'),
('vitalism'),
('voice to skull'),
('voter fraud'),
('voter suppression'),
('voting machine added votes'),
('voting machine algorithm'),
('voting machine changed votes'),
('voting machine deleted votes'),
('voting machine flipped votes'),
('voting machine hacked'),
('voting machine manipulated'),
('voting machine rigged'),
('voting machine switched votes'),
('vulnerability'),
('wake up'),
('wake up call'),
('war gamed'),
('warped'),
('warning'),
('washed'),
('waste'),
('watchword'),
('water contamination planned'),
('water fluoridation compliance'),
('water fluoridation danger'),
('water fluoridation docility'),
('water fluoridation dumbing down'),
('water fluoridation mind control'),
('water fluoridation obedience'),
('water fluoridation pacification'),
('water fluoridation poison'),
('water fluoridation submission'),
('water fluoridation toxic'),
('water poisoning planned'),
('water pollution planned'),
('water supply control planned'),
('water supply corporatization planned'),
('water supply manipulation planned'),
('water supply monopolization planned'),
('water supply privatization planned'),
('water supply rationing planned'),
('water supply restriction planned'),
('weak point'),
('wealth confiscation imminent'),
('weaponized information'),
('weaponized narrative'),
('weather modification'),
('whataboutery'),
('whataboutism'),
('whistleblower'),
('white board'),
('white propaganda'),
('white washed'),
('whitewashed'),
('wiped'),
('witch hunt'),
('withdrawn'),
('wolf in sheep''s clothing'),
('worm'),
('worship'),
('wrong think'),
('yellow journalism'),
('zealot'),
('zero day'),
('zombie claim');